plugin_repo(
    name = "proto",
    revision = "v0.4.0",
    owner = "please-build",
)

plugin_repo(
    name = "go",
    revision = "v1.17.2",
    owner = "please-build",
)

plugin_repo(
    name = "python",
    revision = "v1.6.0",
    owner = "please-build",
)
